import os

Import('base_env PREFIX')

mpaudecSources = map(
    lambda n: os.path.join('mpaudec', n),
    SConscript('mpaudec/SConscript'))

sources = Split("""
    basic_source.cpp
    debug.cpp
    device.cpp
    device_al.cpp
    device_mixer.cpp
    device_null.cpp
    dumb_resample.cpp
    file_ansi.cpp
    input.cpp
    input_aiff.cpp
    input_flac.cpp
    input_mp3.cpp
    input_ogg.cpp
    input_wav.cpp
    loop_point_source.cpp
    memory_file.cpp
    noise.cpp
    resampler.cpp
    sample_buffer.cpp
    sound_effect.cpp
    square_wave.cpp
    sound.cpp
    threads_posix.cpp
    timer_posix.cpp
    tone.cpp
    utility.cpp
    version.cpp
""") + mpaudecSources

env = base_env.Copy()

target = env.Library('audiere', sources)

env.Install(os.path.join(PREFIX, 'include'), 'audiere.h')
env.Install(os.path.join(PREFIX, 'lib32'), target)
